name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: er28-0652/setup-ghidra@master
        with:
          version: "10.1"

      - name: Build with Gradle
        run: gradle buildExtension

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
