# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: er28-0652/setup-ghidra@master
        with:
                version: "10.1"

      - name: Build Extension
        run: gradle buildExtension

      - name: Upload built extension as artifact for debugging
        uses: actions/upload-artifact@v2
        with:
                path: ./dist/*zip
                retention-days: 1

      - name: Install Extension
        run: unzip ./dist/*zip -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions

      - name: Run Tests
        run: echo "Execute your tests here!"